## Numpy

NumPy is a core library for numerical computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [34]:
import numpy as np

### Why NumPy?
- ML models operate on tensors of numbers — weights, gradients, batches of data. NumPy arrays are the standard in-memory representation for that.
- Operations are implemented in C under the hood, so they run far faster than equivalent pure-Python loops.
- Provides a consistent API for linear algebra, broadcasting, and statistics that the rest of the ML ecosystem builds on.

### Why is NumPy faster than Python lists?

| | Python List | NumPy Array |
|---|---|---|
| **Storage** | Array of pointers to scattered Python objects | Contiguous block of same-type values |
| **Type** | Heterogeneous (mixed types allowed) | Homogeneous (single dtype) |
| **Operations** | Element-wise ops need explicit Python loops | Vectorized — loops run in compiled C |
| **Memory overhead** | High (each int is a full Python object) | Low (fixed-size raw values) |
| **Speed** | Slower — interpreter overhead per element | Much faster — no per-element interpreter overhead |

> **Interview Tip:** If asked "why is NumPy fast," the two words to say are **contiguous memory** and **vectorization** (C-level loops instead of Python-level loops).

In [35]:
## create arrays using numpy
## create a 1D array

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)

[10 20 30 40 50]


In [36]:
print(type(arr1))

<class 'numpy.ndarray'>


In [37]:
arr1.shape

(5,)

In [39]:
zeroes = np.zeros((2, 3))
print(zeroes)

[[0. 0. 0.]
 [0. 0. 0.]]


In [40]:
ones = np.ones((3, 4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
arr2 = np.array([10, 20, 30, 40, 50])
arr3 = arr2.reshape(1, 5)


In [7]:
print(arr3.shape)
print(arr3)

(1, 5)
[[10 20 30 40 50]]


In [8]:
## 2D array
arr4 = np.array([[10, 20, 30, 40, 50], [60, 70, 80, 90, 100]])
print(arr4)
print(arr4.shape)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
(2, 5)


In [9]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [44]:
## identity matrix
identity = np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [45]:
# np.linspace() - sequence generator using a fixed COUNT of evenly spaced points
lin = np.linspace(0, 1, 5)  # start, stop (inclusive), number of points
print(lin)

[0.   0.25 0.5  0.75 1.  ]


In [12]:
## Attributes of numpy
arr = np.array([[11, 22, 33], [44, 55, 66]])

print("Array: \n", arr)
print("Shape: ", arr.shape)
print("Number of dimensions: ", arr.ndim)
print("Size (number of elements): ", arr.size)
print("Data type: ", arr.dtype)
print("Item size (in bytes): ", arr.itemsize)

Array: 
 [[11 22 33]
 [44 55 66]]
Shape:  (2, 3)
Number of dimensions:  2
Size (number of elements):  6
Data type:  int64
Item size (in bytes):  8


**Key Points**
- `shape` — tuple of the array's dimensions, e.g. `(2, 3)` = 2 rows, 3 columns. The single most-used attribute for debugging ML pipelines.
- `size` — total element count = product of `shape`.
- `ndim` — number of axes (1D, 2D, 3D...). `len(shape) == ndim`.
- `dtype` — element type (`int64`, `float32`, etc.) — matters a lot for memory usage and GPU compatibility in deep learning.

**Interview Tip:** `.shape` mismatches are the single most common source of runtime bugs in ML code — always know this attribute cold.

In [13]:
## Numpy Vectorized Operation

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

## Element wise addition
print("Addition: ", arr1+arr2)

Addition:  [11 22 33 44 55]


In [14]:
## Element wise subtraction

print("Subtraction: ", arr2-arr1)

Subtraction:  [ 9 18 27 36 45]


In [15]:
## Element wise multiplication

print("Multiplication: ", arr1*arr2)

Multiplication:  [ 10  40  90 160 250]


In [16]:
## Element wise division

print("Division: ", arr1/arr2)

Division:  [0.1 0.1 0.1 0.1 0.1]


In [17]:
## Universal functions

arr = np.array([1, 4, 9, 16, 25])
## square root
print(np.sqrt(arr))

[1. 2. 3. 4. 5.]


In [18]:
## Exponential

print(np.exp(arr))

[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]


In [19]:
## sine function
print(np.sin(arr))

[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]


In [20]:
## log function
print(np.log(arr))

[0.         1.38629436 2.19722458 2.77258872 3.21887582]


In [21]:
## array slicing and indexing

my_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array: \n", my_arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
print(my_arr[0][1])

2


In [23]:
print(my_arr[1:, 2:])

[[ 7  8]
 [11 12]]


In [24]:
## Modify array elements

my_arr[0, 0] = 100
print(my_arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [46]:
# Fancy indexing - select elements using a list/array of indices
data = np.array([100, 200, 300, 400, 500])
indices = [0, 2, 4]
print(data[indices])   # picks elements at index 0, 2, 4

# fancy indexing on 2D arrays
arr2d = np.array([[1, 2], [3, 4], [5, 6]])
print(arr2d[[0, 2]])   # rows 0 and 2

[100 300 500]
[[1 2]
 [5 6]]


In [25]:
data = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99, 110])

## Mean
mean = np.mean(data)
print("Mean: ", mean)

## Median
median = np.median(data)
print("Median: ", median)

## Standard Deviation
std_dev = np.std(data)
print("Standard Deviation: ", std_dev)

## Variance
variance = np.var(data)
print("Variance: ", variance)

Mean:  60.5
Median:  60.5
Standard Deviation:  31.595094555959157
Variance:  998.25


In [30]:
## Logical Operation

data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

data[(data>50) & (data <= 90)]

array([60, 70, 80, 90])

**Key Points**
- Slicing (`arr[1:4]`) returns a **view**, not a copy — modifying the slice modifies the original array.
- Boolean indexing returns a **copy**, and is the standard way to filter data (e.g. `X[y == 1]` to select one class).
- Fancy indexing (indexing with a list/array) also returns a **copy**.

**Common Mistake:** Forgetting that basic slicing shares memory with the original array — an unexpected in-place edit on a "copy" is often actually a slice.