## Numpy: Absolute Basics

In [1]:
import numpy as np

In [2]:
values = np.array([[11, 22, 33], [44, 55, 66]])
print(values)
print(values.shape)

[[11 22 33]
 [44 55 66]]
(2, 3)


In [3]:
print(values[1])

[44 55 66]


In [4]:
values[0,0] = 10
print(values)

[[10 22 33]
 [44 55 66]]


In [5]:
values2 = np.array([[11, 22, 33, 44], [10, 20, 30, 40], [55, 66, 77, 88]])

print(values2)

[[11 22 33 44]
 [10 20 30 40]
 [55 66 77 88]]


In [6]:
values2.ndim

2

In [7]:
values2.shape

(3, 4)

In [8]:
values2.size

12

In [9]:
values.dtype

dtype('int64')

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.empty(3)

array([1., 1., 1.])

In [13]:
np.arange(2, 7, 3)

array([2, 5])

In [14]:
np.linspace(0, 10, num=6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [15]:
x = np.ones(3, dtype=np.int64)
print(x)

[1 1 1]


In [16]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))


[1 2 3 4 5 6 7 8]


In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(np.concatenate((a, b)))

[1 2 3 4 5 6 7 8]


In [18]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

print(np.concatenate((x, y), axis=0))

[[1 2]
 [3 4]
 [5 6]]


In [19]:
b = values2.reshape(4, 3)
print(b)

[[11 22 33]
 [44 10 20]
 [30 40 55]
 [66 77 88]]


In [20]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)

(6,)


In [21]:
a2 = a[np.newaxis, :]
print(a2)
print(a2.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [22]:
b = np.expand_dims(a, axis=1)
print(b.shape)
print(b)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [23]:
c = np.expand_dims(a, axis=0)
print(c.shape)
print(c)

(1, 6)
[[1 2 3 4 5 6]]


## Indexing and Slicing

In [24]:
data = np.array([1, 2, 3])
print(data[1])

2


In [25]:
print(data[0:2])

[1 2]


In [26]:
data[1:]

array([2, 3])

In [27]:
data[-2:]

array([2, 3])

In [28]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a<5])

[1 2 3 4]


In [29]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [30]:
divisible_by_2 = a[a%2 == 0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [31]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [32]:
five_up = (a > 5) | (a == 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [33]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


## How to create an array from existing data


In [34]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99, 110])

print(a)

[ 11  22  33  44  55  66  77  88  99 110]


In [35]:
arr1 = a[3: 8]
print(arr1)

[44 55 66 77 88]


In [36]:
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])

print(np.vstack((a1, a2)))

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [37]:
print(np.hstack((a1, a2)))

[[1 1 3 3]
 [2 2 4 4]]


In [38]:
x = np.arange(1, 25).reshape(2, 12)

print(np.hsplit(x, (3, 4)))

[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]


In [41]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [42]:
b1 = a[0, :]
print(b1)

[1 2 3 4]


In [44]:
b1[0] = 99
print(b1)

[99  2  3  4]


In [45]:
b2 = a.copy()
print(b2)

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Basic array operations

In [39]:
data = np.array([1, 2])
ones = np.ones(2, dtype=np.int_)


In [40]:
print(data + ones)

[2 3]


In [46]:
data - ones

array([0, 1])

In [47]:
data * data

array([1, 4])

In [48]:
data / data

array([1., 1.])

In [49]:
a = np.array([1, 2, 3, 4])
print(a.sum())

10


In [50]:
b = np.array([[1, 1], [2, 2]])
print(b.sum(axis=0))

[3 3]


In [51]:
print(b.sum(axis=1))

[2 4]


## Broadcasting

There are times when you might want to carry out an operation between an array and a single number or between arrays of two different sizes. This is called Broadcasting.

- Mechanism that allows `Numpy` to perform operations on arrays of different shapes.

## More useful array operations

In [53]:
data = np.array([1, 2, 3])
print(data.max())

3


In [54]:
data.min()

np.int64(1)

In [55]:
data.sum()

np.int64(6)

In [57]:
rng = np.random.default_rng()
rng.random(4)

array([0.76394498, 0.03753143, 0.53148633, 0.95684676])

In [58]:
rng.random((3, 2))

array([[0.47379472, 0.46456736],
       [0.61457876, 0.76090294],
       [0.17695838, 0.16472701]])

In [59]:
## Generating random numbers

rng.integers(5, size=(2, 4))

array([[2, 4, 1, 1],
       [2, 0, 4, 4]])

## How to get unique items and counts

In [63]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
print(a)

[11 11 12 13 14 15 16 17 12 13 11 14 18 19 20]


In [61]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [64]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [65]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]
