# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


In [3]:
import numpy as np

In [4]:
my_arr = np.random.randint(1, 21, size = (5, 5))
print(my_arr)

my_arr[:, 2] = 1
print("\nModified array: ", my_arr)

[[ 7  2 16  7 12]
 [13  9  5  7  7]
 [11  7 15 11 14]
 [19  8  5 12  3]
 [19 15 20 15 20]]

Modified array:  [[ 7  2  1  7 12]
 [13  9  1  7  7]
 [11  7  1 11 14]
 [19  8  1 12  3]
 [19 15  1 15 20]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [5]:
values = np.arange(1, 17).reshape(4, 4)
print("Values: ", values)

## Replace the diagonal elements with 0
np.fill_diagonal(values, 0)
print("\nModified array: ", values)


Values:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Modified array:  [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [6]:
values = np.arange(1, 37).reshape(6, 6)
print(values)

extracted_arr1 = values[2:5, 1:4]
print(f"\nThe extracted array is: {extracted_arr1}")

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

The extracted array is: [[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [7]:
val1 = np.random.default_rng()
my_val = val1.random(25).reshape(5,5)
print(my_val)

top = my_val[0, :]
bottom = my_val[-1, :]
left = my_val[1:-1,0]
right = my_val[1:-1, -1]

print(f"TOP: ", top)
print(f"BOTTOM: ",bottom)
print(f"LEFT: ", left)
print(f"RIGHT: ", right)

border_elements = np.concatenate([top, bottom, left, right])
print(f"Border elements: ", border_elements)

[[0.70606536 0.28079983 0.50180077 0.8444137  0.59831969]
 [0.17522283 0.83996856 0.39570066 0.69092401 0.43117827]
 [0.19296171 0.06185997 0.44751385 0.08448696 0.51300166]
 [0.63787969 0.76003368 0.79267016 0.66856232 0.38931873]
 [0.11993051 0.79667559 0.22071417 0.44966706 0.68371108]]
TOP:  [0.70606536 0.28079983 0.50180077 0.8444137  0.59831969]
BOTTOM:  [0.11993051 0.79667559 0.22071417 0.44966706 0.68371108]
LEFT:  [0.17522283 0.19296171 0.63787969]
RIGHT:  [0.43117827 0.51300166 0.38931873]
Border elements:  [0.70606536 0.28079983 0.50180077 0.8444137  0.59831969 0.11993051
 0.79667559 0.22071417 0.44966706 0.68371108 0.17522283 0.19296171
 0.63787969 0.43117827 0.51300166 0.38931873]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [8]:
arr1 = np.random.randint(1, 11, size = (3, 4))
arr2 = np.random.randint(1, 11, size = (3, 4))

print(f"Array 1:\n {arr1}\n")
print(f"Array 2:\n {arr2}\n")
print(f" Element-wise Addition: \n {arr1 + arr2}")
print(f" Element-wise Subtraction: \n {arr1 - arr2}")
print(f" Element-wise Multiplication: \n {arr1 * arr2}")
print(f" Element-wise Division: \n {arr1 / arr2}")


Array 1:
 [[ 5  8  3  8]
 [ 4  4  4  8]
 [ 2  6  8 10]]

Array 2:
 [[ 8 10 10 10]
 [ 5  3  7 10]
 [ 3  9  1 10]]

 Element-wise Addition: 
 [[13 18 13 18]
 [ 9  7 11 18]
 [ 5 15  9 20]]
 Element-wise Subtraction: 
 [[-3 -2 -7 -2]
 [-1  1 -3 -2]
 [-1 -3  7  0]]
 Element-wise Multiplication: 
 [[ 40  80  30  80]
 [ 20  12  28  80]
 [  6  54   8 100]]
 Element-wise Division: 
 [[0.625      0.8        0.3        0.8       ]
 [0.8        1.33333333 0.57142857 0.8       ]
 [0.66666667 0.66666667 8.         1.        ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [12]:
my_arr2 = np.arange(1, 17).reshape(4, 4)
print(my_arr2)

print(f"Row-wise sum: ", my_arr2.sum(axis=0))
print(f"Column-wise sum: ", my_arr2.sum(axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:  [28 32 36 40]
Column-wise sum:  [10 26 42 58]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [17]:
my_arr3 = np.random.randint(1, 21, size=(5, 5))
print(my_arr3)


mean = np.mean(my_arr3)
median = np.median(my_arr3)
std_dev = np.std(my_arr3)
variance = np.var(my_arr3)

print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Standard Deviation: {std_dev}")
print(f"Variance: {variance}")


[[16 12 20 14 18]
 [ 9  1  6 17 12]
 [13 16 20 13 10]
 [17 19 19 15  1]
 [ 1  6  8  2  2]]
Mean: 11.48
Median: 13.0
Standard Deviation: 6.375703882709736
Variance: 40.6496


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [21]:
my_arr4 = np.arange(1, 10).reshape(3, 3)
print(my_arr4)

mean = np.mean(my_arr4)
std_dev = np.std(my_arr4)
normalized_array = (my_arr4 - mean) / std_dev
print(f'Normalized array: \n', normalized_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array: 
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [24]:
arr1 = np.random.randint(1, 10, size=(3, 3))
print(f"Original array: ", arr1)

row_array = np.random.randint(1, 11, size=(3,))
print(f"Row array: ", row_array)

result = arr1 + row_array
print(f"Result: ", result)


Original array:  [[7 4 1]
 [1 7 5]
 [1 7 8]]
Row array:  [6 2 6]
Result:  [[13  6  7]
 [ 7  9 11]
 [ 7  9 14]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [25]:
arr1 = np.random.randint(1, 17, size=(4, 4))
print(f"Original array: ", arr1)

column_arr = np.random.randint(1, 12, size=(4,))
print(f"Column-array: ", column_arr)

modified_arr = arr1 - column_arr[:, np.newaxis]
print(f"Modified array: ", modified_arr)

Original array:  [[15 14 13  2]
 [ 3 12  3 12]
 [ 2  1 15  8]
 [12 15 15  6]]
Column-array:  [6 2 3 8]
Modified array:  [[ 9  8  7 -4]
 [ 1 10  1 10]
 [-1 -2 12  5]
 [ 4  7  7 -2]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [31]:
matrix = np.random.randint(1, 11, size=(3,3))
print("Original matrix: \n", matrix)

determinant = np.linalg.det(matrix)
print(f"Determinant: ", determinant)

transposed_matrix = np.transpose(matrix)
print(f"Transposed matrix: ", transposed_matrix)

inverse = np.linalg.inv(matrix)
print(f"Inverse of a matrix: ", inverse)

eigens = np.linalg.eigvals(matrix)
print(f"Eigen values: ", eigens)

Original matrix: 
 [[ 8  7  4]
 [10  5  8]
 [ 2  9  2]]
Determinant:  -203.99999999999994
Transposed matrix:  [[ 8 10  2]
 [ 7  5  9]
 [ 4  8  2]]
Inverse of a matrix:  [[ 0.30392157 -0.10784314 -0.17647059]
 [ 0.01960784 -0.03921569  0.11764706]
 [-0.39215686  0.28431373  0.14705882]]
Eigen values:  [18.87731869  1.87775514 -5.75507383]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [33]:
arr1 = np.random.randint(1, 11, size=(2, 3))
arr2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1: ", arr1)
print("Array 2: ", arr2)

print("Matrix Multiplication: ", np.dot(arr1, arr2))


Array 1:  [[ 7  4  9]
 [10  2  3]]
Array 2:  [[ 6  4]
 [ 5 10]
 [ 6  8]]
Matrix Multiplication:  [[116 140]
 [ 88  84]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [38]:
arr1 = np.arange(1, 10).reshape(3, 3)
print(arr1)

arr2 = arr1.reshape(1, 9)
print(f"Modified array: ", arr2)

arr3 = arr2.reshape(9, 1)
print(f"Modified array: ", arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Modified array:  [[1 2 3 4 5 6 7 8 9]]
Modified array:  [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [41]:
arr1 = np.random.randint(1, 26, size=(5, 5))
print(f"Original array: ", arr1)

flattened_arr = arr1.flatten()
print(f"Flattened array: ", flattened_arr)

reshaped_arr = flattened_arr.reshape(5, 5)
print(f"Reshaped array: ", reshaped_arr)

Original array:  [[ 5 13  7 25 20]
 [12 11 24 20 13]
 [ 8 16 22  1 15]
 [23  1 25 17 20]
 [ 7 25 23  2  4]]
Flattened array:  [ 5 13  7 25 20 12 11 24 20 13  8 16 22  1 15 23  1 25 17 20  7 25 23  2
  4]
Reshaped array:  [[ 5 13  7 25 20]
 [12 11 24 20 13]
 [ 8 16 22  1 15]
 [23  1 25 17 20]
 [ 7 25 23  2  4]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [43]:
arr1 = np.random.randint(1, 21, size=(5, 5))
print(f"Original array: ", arr1)

extracted_indices = arr1[[0, 0, -1, -1], [0, -1, 0, -1]]
print(f"Corner elements: ", extracted_indices)

Original array:  [[16 15 15  7 11]
 [ 5 11  4  4  3]
 [19  4  5  7 13]
 [12 13 13 13 12]
 [10 10 18 16 13]]
Corner elements:  [16 11 10 13]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [47]:
arr1 = np.random.randint(1, 21, size=(4, 4))
print(f"Original array: ", arr1)

arr2 = arr1.copy()
arr2[arr1>10] = 10
print(f"Modified array: ", arr2)

Original array:  [[ 4  1 14 15]
 [17 13  9  1]
 [14  1  9 19]
 [ 5 13 15  2]]
Modified array:  [[ 4  1 10 10]
 [10 10  9  1]
 [10  1  9 10]
 [ 5 10 10  2]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [52]:
dtype = [('name', 'U10'), ('age', 'i8'), ('weight', 'f8')]

data = [('Alice', 30, 58.6), ('Bob', 25, 68.9), ('Charlie', 32, 63)]

structured_array = np.array(data, dtype)
print(f"Structured Array:\n", structured_array)

sorted_data = np.sort(structured_array, order='age')
print(f"Sorted array by age: ", sorted_data)

Structured Array:
 [('Alice', 30, 58.6) ('Bob', 25, 68.9) ('Charlie', 32, 63. )]
Sorted array by age:  [('Bob', 25, 68.9) ('Alice', 30, 58.6) ('Charlie', 32, 63. )]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [54]:
dtype = [('x', 'i8'), ('y', 'i8')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=dtype)

distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [ ]:
import numpy.ma as ma 

array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[20  3 17 10]
 [13 11  8 12]
 [10  6 19 12]
 [ 6  9 18 17]]
Masked array:
[[-- 3 -- 10]
 [-- -- 8 --]
 [10 6 -- --]
 [6 9 -- --]]
Sum of unmasked elements: 52


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [56]:
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)


mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[ 9  3  1]
 [ 3  9  2]
 [ 2  7 15]]
Masked array:
[[-- 3 1]
 [3 -- 2]
 [2 7 --]]
Modified masked array:
[[3 3 1]
 [3 3 2]
 [2 7 3]]
